[display]
code_editor_font_size = 14
default_width = "medium"
default_table_page_size = 10
cell_output = "below"
dataframes = "rich"
reference_highlighting = false
default_table_max_columns = 50
theme = "system"

[server]
browser = "default"
follow_symlink = false

[keymap]
destructive_delete = true
preset = "vim"

[keymap.overrides]

[completion]
activate_on_typing = true
copilot = false

[experimental]

[formatting]
line_length = 120

[package_management]
manager = "uv"

[mcp]
presets = []

[mcp.mcpServers]

[diagnostics]
sql_linter = true

[language_servers.ty]

[language_servers.basedpyright]
enabled = false

[language_servers.pylsp]
enable_mypy = true
enable_flake8 = false
enabled = true
enable_ruff = true
enable_pyflakes = false
enable_pydocstyle = false
enable_pylint = false

[datasources]

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false

[ai]
inline_tooltip = false
mode = "manual"
rules = ""

[ai.models]
edit_model = "ollama/qwen2.5-coder:7b-instruct-q5_K_M"
autocomplete_model = "ollama/qwen2.5-coder:7b-instruct-q5_K_M"
displayed_models = []
chat_model = "ollama/qwen2.5-coder:7b-instruct-q5_K_M"
custom_models = []

[snippets]
include_default_snippets = true
custom_paths = []

[runtime]
auto_instantiate = false
pythonpath = ["pydata-demo/"]
std_stream_max_bytes = 1000000
output_max_bytes = 8000000
auto_reload = "off"
on_cell_change = "autorun"
dotenv = [".env"]
reactive_tests = true
watcher_on_save = "lazy"
default_auto_download = []
default_sql_output = "auto"
