[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[snippets]
include_default_snippets = true
custom_paths = []

[datasources]

[mcp]
presets = []

[mcp.mcpServers]

[display]
code_editor_font_size = 14
dataframes = "rich"
default_width = "full"
custom_css = [".marimo-theme.css"]
reference_highlighting = false
default_table_page_size = 10
theme = "system"
default_table_max_columns = 50
cell_output = "above"

[runtime]
watcher_on_save = "lazy"
default_sql_output = "auto"
on_cell_change = "autorun"
reactive_tests = true
auto_reload = "off"
auto_instantiate = false
pythonpath = ["pydata-demo"]
default_auto_download = []
dotenv = []
output_max_bytes = 8000000
std_stream_max_bytes = 1000000

[experimental]

[formatting]
line_length = 120

[ai]
inline_tooltip = false
mode = "manual"
rules = ""

[ai.models]
displayed_models = []
custom_models = []
edit_model = "ollama/qwen2.5-coder:1.5b-base-q6_K"
chat_model = "ollama/qwen2.5-coder:1.5b-base-q6_K"
autocomplete_model = "ollama/qwen2.5-coder:1.5b-base-q6_K"

[diagnostics]
sql_linter = true

[keymap]
destructive_delete = true

[keymap.overrides]
"global.commandPalette" = "Cmd-Shift-a"

[server]
browser = "default"
follow_symlink = false

[package_management]
manager = "uv"

[language_servers.basedpyright]
enabled = false

[language_servers.ty]

[language_servers.pylsp]
enable_pylint = false
enable_pyflakes = false
enable_mypy = true
enabled = true
enable_flake8 = false
enable_pydocstyle = false
enable_ruff = true

[completion]
copilot = "custom"
activate_on_typing = true
