[project]
name = "pydata-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graphframes-py==0.10.0",
    "marimo>=0.18.0",
    "pyspark==3.5.5",
]
